//! The application icon, embedded from `assets/icon.rgba`.
//!
//! One 64x64 RGBA buffer feeds both consumers:
//!
//! * the window / taskbar icon (`egui::IconData`, set from `main.rs` before the
//!   first frame so the title bar and Alt-Tab never show a blank icon);
//! * the tray icon (`tray_icon::Icon`).
//!
//! The asset is generated by `assets/generate_icon.py` (checked in, so the
//! build needs no Python) — the palette values in that script mirror
//! `theme::tokens`, which keeps the icon in the app's own colour family.

/// 64x64 RGBA icon, row-major, top-down.
pub const ICON_RGBA: &[u8] = include_bytes!("../assets/icon.rgba");

pub const ICON_SIZE: u32 = 64;

/// The embedded icon as an egui image, for the window/taskbar.
pub fn window_icon() -> egui::IconData {
    egui::IconData {
        rgba: ICON_RGBA.to_vec(),
        width: ICON_SIZE,
        height: ICON_SIZE,
    }
}

/// The embedded icon for the system tray.
pub fn tray_icon() -> tray_icon::Icon {
    tray_icon::Icon::from_rgba(ICON_RGBA.to_vec(), ICON_SIZE, ICON_SIZE)
        .expect("assets/icon.rgba is a valid 64x64 RGBA buffer")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_icon_is_a_complete_rgba_buffer() {
        let expected = (ICON_SIZE * ICON_SIZE * 4) as usize;
        assert_eq!(ICON_RGBA.len(), expected);
        // A transparent icon would mean the generator or the asset path broke.
        let opaque = ICON_RGBA.chunks_exact(4).filter(|px| px[3] > 200).count();
        assert!(
            opaque > (ICON_SIZE * ICON_SIZE / 2) as usize,
            "expected a mostly opaque icon, found {opaque} opaque pixels"
        );
    }

    #[test]
    fn the_window_icon_carries_the_size_egui_needs() {
        let icon = window_icon();
        assert_eq!(icon.width, ICON_SIZE);
        assert_eq!(icon.height, ICON_SIZE);
        assert_eq!(icon.rgba.len(), (ICON_SIZE * ICON_SIZE * 4) as usize);
    }
}
